"""Command line helper: ``manim-radar``.

    manim-radar --version
    manim-radar themes                 # list colour themes
    manim-radar styles                 # list style presets
    manim-radar template my_chart.py   # write a starter scene
    manim-radar demo --render          # render the bundled demo reel
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import textwrap

from . import __version__

TEMPLATE = '''# -*- coding: utf-8 -*-
"""Starter scene generated by ``manim-radar template``."""

from manim import *
from manim_radar import DeepSpace, RadarChart, RadarData, RadarReel, set_scene_background

AXES = ["Speed", "Power", "Range", "Comfort", "Price", "Safety"]

SNAPSHOTS = [
    RadarData(axes=AXES, values=[8, 6, 7, 9, 5, 8], name="Model A", color="#17B8BA"),
    RadarData(axes=AXES, values=[6, 9, 5, 7, 8, 9], name="Model B", color="#E868C8"),
    RadarData(axes=AXES, values=[9, 9, 8, 9, 9, 9], name="Model C", color="#FFD166"),
]


class MyRadar(Scene):
    def construct(self):
        set_scene_background("{theme}")
        chart = RadarChart(
            SNAPSHOTS[0],
            style="{style}",
            theme="{theme}",
            title="Six axes",
        )
        # One command plays the whole sequence (switch snapshots, hold, fade out).
        RadarReel(chart, SNAPSHOTS, hold=0.6, backdrop=True).play_on(self)
'''

DEMO_COMMAND = "manim -qh examples/legacy_v2.py RadarV2Scene"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="manim-radar", description="Animated radar charts for Manim."
    )
    parser.add_argument("--version", action="version", version=f"manim-radar {__version__}")
    sub = parser.add_subparsers(dest="command")

    sub.add_parser("themes", help="list colour themes")
    sub.add_parser("styles", help="list style presets")

    tpl = sub.add_parser("template", help="write a starter scene file")
    tpl.add_argument("output", nargs="?", default="my_radar.py", help="file to create")
    tpl.add_argument("--style", default="neo", help="style preset (default: neo)")
    tpl.add_argument("--theme", default="midnight", help="colour theme (default: midnight)")
    tpl.add_argument("--force", action="store_true", help="overwrite an existing file")

    demo = sub.add_parser("demo", help="where the bundled demo lives / render it")
    demo.add_argument("--render", action="store_true", help="run manim on the demo reel")
    demo.add_argument("-q", "--quality", default="-ql", help="manim quality flag (-ql/-qh)")
    return parser


def main(argv=None) -> int:
    args = build_parser().parse_args(argv)

    if args.command == "themes":
        from .theme import THEMES

        width = max(len(n) for n in THEMES)
        for name, theme in THEMES.items():
            print(f"  {name:<{width}}  bg={theme.background}  grid={theme.grid}")
        return 0

    if args.command == "styles":
        from .config import STYLES

        for name, cfg in STYLES.items():
            extras = []
            if cfg.rainbow_edges:
                extras.append("rainbow outline")
            if cfg.vertex_dots:
                extras.append("vertex dots")
            if cfg.sweep:
                extras.append("sweep beam")
            if cfg.stepped:
                extras.append("snap-in numbers")
            print(f"  {name:<9} r={cfg.radius}  levels={cfg.levels}  {', '.join(extras)}")
        return 0

    if args.command == "template":
        if os.path.exists(args.output) and not args.force:
            print(f"refusing to overwrite {args.output!r} (use --force)", file=sys.stderr)
            return 1
        with open(args.output, "w", encoding="utf-8") as fh:
            fh.write(TEMPLATE.format(style=args.style, theme=args.theme))
        print(f"wrote {args.output}")
        print(f"render it with:  manim -qh {args.output} MyRadar")
        return 0

    if args.command == "demo":
        here = os.path.dirname(os.path.abspath(__file__))
        demo_file = os.path.join(os.path.dirname(os.path.dirname(here)), "examples", "legacy_v2.py")
        if not os.path.exists(demo_file):
            print("the bundled demo file is not available in this installation;")
            print("grab it from the source distribution or the repository:")
            print("  https://github.com/FTZ-OPUS/manim-radar")
            return 1
        print(f"demo scene:  {demo_file}")
        if args.render:
            cmd = ["manim", args.quality, demo_file, "RadarV2Scene"]
            print("running:", " ".join(cmd))
            return subprocess.call(cmd)
        print(f"render it with:  {DEMO_COMMAND}")
        return 0

    print(textwrap.dedent(
        """\
        manim-radar — animated radar charts for Manim

        usage:
          manim-radar themes                 list colour themes
          manim-radar styles                 list style presets
          manim-radar template my_chart.py   write a starter scene
          manim-radar demo --render          render the bundled demo reel
        """
    ))
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
